-- 1. Profiles (Extensions to Auth)
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  username text,
  avatar_url text,
  role text default 'franchise',
  franchise_id int, -- Legacy link
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Community Posts
create table public.community_posts (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  content_text text,
  image_url text,
  likes_count int default 0,
  comments_count int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Friendships
create table public.friendships (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  friend_id uuid references public.profiles(id) not null,
  status text check (status in ('pending', 'accepted', 'rejected')) default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, friend_id)
);

-- 4. Chat Messages (Realtime!)
create table public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid references public.profiles(id) not null,
  receiver_id uuid references public.profiles(id) not null,
  content text,
  attachment_url text,
  status text default 'sent', -- sent, delivered, read
  read_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
