CREATE TABLE IF NOT EXISTS franchise_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    city TEXT NOT NULL,
    state TEXT DEFAULT 'N/A',
    plan_selected TEXT DEFAULT 'standard',
    budget TEXT DEFAULT 'N/A',
    status TEXT DEFAULT 'pending',
    aadhar_url TEXT,
    agreement_accepted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    upi_id TEXT,
    bank_account_number TEXT,
    ifsc_code TEXT,
    bank_name TEXT
);

CREATE TABLE IF NOT EXISTS site_content (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section TEXT NOT NULL,
    content_key TEXT NOT NULL,
    content_value TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS site_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key TEXT NOT NULL UNIQUE,
    setting_value TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insert some default/sample content to avoid empty page
INSERT INTO site_content (section, content_key, content_value) VALUES
('hero', 'title', 'Build Your Legacy with The Kada Franchise'),
('hero', 'subtitle', 'Join the fastest growing hyperlocal marketplace network in India.'),
('features', 'list', '[{"title": "Low Investment", "desc": "Start with minimal capital."}, {"title": "High Returns", "desc": "Earn up to 30% ROI."}]')
ON CONFLICT DO NOTHING;

